/* Farmaville — página institucional baseada exclusivamente nos dados confirmados pela farmácia. */
import { ArrowLeft, ArrowUpRight, BadgeCheck, Clock3, MapPin, MessageCircle, Store } from "lucide-react";
import { Link } from "wouter";

const whatsappUrl = "https://wa.me/5562991089398?text=" + encodeURIComponent("Olá, Farmaville! Preciso de atendimento.");
const mapsUrl = "https://www.google.com/maps/search/?api=1&query=Av.+Goiás,+2641,+Vila+Brasil,+Anápolis,+GO,+75144-355";

export default function About() {
  return <div className="info-page"><header className="info-header"><Link href="/" className="back-link"><ArrowLeft size={16} /> Voltar para a Farmaville</Link><Link href="/" className="product-page-brand"><img src="/manus-storage/logo-oficial_5f581676.png" alt="Farmaville Farmácia" /></Link><Link href="/conta" className="product-cart-link">Minha conta</Link></header><main className="info-main"><section className="info-hero"><div><span className="section-label">farmácia de bairro, cuidado por perto</span><h1>Uma Farmaville<br /><em>para a sua rotina.</em></h1><p>A Farmaville reúne medicamentos, bem-estar e atendimento próximo em Anápolis. No site, você encontra o catálogo e organiza sua compra; a confirmação de disponibilidade, entrega, retirada e receitas é feita pela equipe da loja.</p><div className="info-actions"><a href={whatsappUrl} target="_blank" rel="noreferrer" className="button button-dark">Falar com a equipe <MessageCircle size={16} /></a><a href={mapsUrl} target="_blank" rel="noreferrer" className="outline-link">Como chegar <ArrowUpRight size={16} /></a></div></div><img src="/manus-storage/fachada-interior_832aefad.jpg" alt="Fachada e interior da Farmaville em Anápolis" /></section><section className="info-facts"><div><MapPin size={20} /><span><small>Endereço</small><strong>Av. Goiás, 2641 · Vila Brasil</strong><em>Anápolis — GO · CEP 75144-355</em></span></div><div><Clock3 size={20} /><span><small>Horários</small><strong>Seg–sex · 8h às 19h</strong><em>Sábado · 8h às 13h · domingo fechado</em></span></div><div><BadgeCheck size={20} /><span><small>Atendimento farmacêutico informado</small><strong>Lucas Antônio · CRF-GO 11193</strong><em>Orientação e confirmações pela equipe</em></span></div></section><section className="info-story"><img src="/manus-storage/equipe-balcao_c473e999.png" alt="Equipe da Farmaville no balcão de atendimento" /><div><span className="section-label">atendimento com clareza</span><h2>Do balcão para<br /><em>o seu dia a dia.</em></h2><p>Para produtos sujeitos a receita, o envio pelo WhatsApp apenas inicia a avaliação da Farmaville. Ele não confirma aprovação, disponibilidade ou venda automática.</p><Link href="/privacidade" className="outline-link">Ver regras de receitas e privacidade <ArrowUpRight size={16} /></Link></div></section><section className="info-next"><Store size={23} /><div><h2>Quer planejar sua compra?</h2><p>Monte a sacola, confira o valor estimado e escolha a opção de entrega ou retirada. Antes de concluir, a equipe confirma as informações operacionais.</p></div><Link href="/carrinho" className="button button-dark">Ir para a sacola <ArrowUpRight size={16} /></Link></section></main></div>;
}
