/* Farmaville — área da conta: identidade real, desejos locais e preparação para pedidos concluídos. */
import { ArrowLeft, BookHeart, LogOut, PackageCheck, ShoppingBag, UserRound } from "lucide-react";
import { Link } from "wouter";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { useShop } from "@/contexts/ShopContext";
import { trpc } from "@/lib/trpc";

export default function Account() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  const { wishlist, cartCount } = useShop();
  const ordersQuery = trpc.orders.mine.useQuery(undefined, { enabled: isAuthenticated });
  if (loading) return <div className="account-loading">Preparando sua área…</div>;
  if (!isAuthenticated) return <div className="info-page"><header className="info-header"><Link href="/" className="back-link"><ArrowLeft size={16} /> Voltar para a Farmaville</Link><Link href="/" className="product-page-brand"><img src="/manus-storage/logo-oficial_5f581676.png" alt="Farmaville Farmácia" /></Link></header><main className="account-gate"><UserRound size={30} /><span className="section-label">sua conta farmaville</span><h1>Entre para manter<br /><em>sua compra por perto.</em></h1><p>Ao entrar, você poderá acessar sua área de conta. Seus desejos e sua sacola atual continuam disponíveis neste dispositivo.</p><button type="button" className="button button-dark" onClick={startLogin}>Entrar na minha conta <ArrowLeft size={16} /></button></main></div>;
  return <div className="info-page"><header className="info-header"><Link href="/" className="back-link"><ArrowLeft size={16} /> Voltar para a Farmaville</Link><Link href="/" className="product-page-brand"><img src="/manus-storage/logo-oficial_5f581676.png" alt="Farmaville Farmácia" /></Link><button type="button" className="product-cart-link" onClick={logout}>Sair <LogOut size={16} /></button></header><main className="account-main"><section className="account-hero"><span className="section-label">minha conta</span><h1>Olá, <em>{user?.name || "cliente"}.</em></h1><p>Este é o seu espaço para acompanhar compras concluídas e retomar seus produtos salvos.</p></section><section className="account-cards"><Link href="/desejos"><BookHeart size={22} /><span><small>Produtos salvos neste dispositivo</small><strong>{wishlist.length} {wishlist.length === 1 ? "item em desejos" : "itens em desejos"}</strong></span><ArrowLeft size={17} /></Link><Link href="/carrinho"><ShoppingBag size={22} /><span><small>Sacola atual</small><strong>{cartCount} {cartCount === 1 ? "item na sacola" : "itens na sacola"}</strong></span><ArrowLeft size={17} /></Link></section><section className="account-orders"><PackageCheck size={24} /><span className="section-label">meus pedidos</span>{ordersQuery.isLoading ? <><h2>Consultando seus pedidos…</h2><p>Aguarde enquanto organizamos o histórico associado à sua conta.</p></> : ordersQuery.data?.length ? <><h2>{ordersQuery.data.length === 1 ? "Você tem 1 pedido acompanhado." : `Você tem ${ordersQuery.data.length} pedidos acompanhados.`}</h2><p>As etapas de pagamento, estoque, entrega e retirada são atualizadas somente após a integração operacional estar ativa.</p></> : <><h2>Ainda não há pedidos vinculados a esta conta.</h2><p>Quando o checkout e a plataforma de vendas estiverem concluídos, seus pedidos confirmados e atualizações de acompanhamento aparecerão aqui.</p></>}<Link href="/#catalogo" className="button button-dark">Explorar o catálogo <ArrowLeft size={16} /></Link></section></main></div>;
}
