/* Farmaville — etapa de checkout estruturada; não processa cobranças antes da ativação do operador. */
import { ArrowLeft, BadgeCheck, CircleAlert, CreditCard, MapPin, ShoppingBag, Store, Truck } from "lucide-react";
import { Link } from "wouter";
import { useShop } from "@/contexts/ShopContext";
import { commerceConfig } from "@/lib/commerce-config";

const formatPrice = (value: number) => `R$ ${value.toFixed(2).replace(".", ",")}`;

export default function Checkout() {
  const { cartLines, subtotal, fulfillment, shipping } = useShop();
  const receiving = fulfillment === "pickup" ? <><Store size={18} /><span><strong>Retirada na loja</strong>Av. Goiás, 2641 · Vila Brasil, Anápolis</span></> : <><Truck size={18} /><span><strong>Entrega em Anápolis</strong>Área atendida, taxa e prazo serão confirmados pela Farmaville.</span></>;
  return <div className="checkout-page"><header className="product-page-header"><div className="page-header-side"><Link href="/carrinho" className="back-link"><ArrowLeft size={16} /> Voltar para a sacola</Link></div><Link href="/" className="product-page-brand"><img src="/manus-storage/logo-oficial_5f581676.png" alt="Farmaville Farmácia" /></Link><Link href="/duvidas" className="product-cart-link">Precisa de ajuda?</Link></header><main className="checkout-main"><section className="checkout-hero"><span className="section-label">etapa de pagamento</span><h1>Estamos preparando<br /><em>seu checkout.</em></h1><p>Esta página organiza a próxima etapa da sua compra. Nenhuma cobrança será feita enquanto a loja, o catálogo e o Mercado Pago estiverem em ativação.</p></section>{cartLines.length === 0 ? <div className="checkout-empty"><ShoppingBag size={26} /><h2>Adicione produtos antes de continuar.</h2><Link href="/#catalogo" className="button button-dark">Ir ao catálogo</Link></div> : <div className="checkout-grid"><div className="checkout-steps"><section><span className="checkout-step">01</span><div><h2>Recebimento</h2><div className="checkout-detail">{receiving}</div></div></section><section><span className="checkout-step">02</span><div><h2>Pagamento</h2><div className="checkout-detail"><CreditCard size={18} /><span><strong>{commerceConfig.payment.provider} via {commerceConfig.payment.platform}</strong>Aguardando reivindicação da loja e conexão do aplicativo pelo titular.</span></div></div></section><section><span className="checkout-step">03</span><div><h2>Confirmação do pedido</h2><div className="checkout-detail"><BadgeCheck size={18} /><span><strong>Confirmação antes da conclusão</strong>Preço, estoque, entrega e itens sujeitos a receita serão revisados pela operação.</span></div></div></section></div><aside className="checkout-summary"><span className="section-label">sua sacola</span>{cartLines.map(({ product, quantity }) => <div className="checkout-item" key={product.code}><span>{quantity}×</span><p>{product.name}<small>Código {product.code}</small></p><strong>{formatPrice(product.price * quantity)}</strong></div>)}<div className="checkout-total"><span>Produtos</span><strong>{formatPrice(subtotal)}</strong></div><div className="checkout-status"><CircleAlert size={16} /><p><strong>Ativação pendente</strong>A loja deve ser reivindicada e o Mercado Pago conectado antes de iniciar pagamentos.</p></div><Link href="/carrinho" className="outline-link">Ajustar minha sacola <ArrowLeft size={15} /></Link></aside></div>}<section className="checkout-location"><MapPin size={20} /><div><strong>Atendimento e retirada em Anápolis</strong><span>Farmaville · Av. Goiás, 2641 · Vila Brasil · Lucas Antônio · CRF-GO 11193</span></div></section></main></div>;
}
